apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{.NetworkName}}
  namespace: {{.NetworkNamespace}}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{.CniResourceName}}
    sriovnetwork.openshift.io/owner-ref: {{.Owner}}
spec:
  config: '{
  "cniVersion":"1.0.0",
  "name":"{{.NetworkName}}",
{{- if .MetaPluginsConfigured -}}
  "plugins": [
    {
{{- end -}}
  "type":"{{.CniType}}",
{{- if .CapabilitiesConfigured -}}
  "capabilities":{{.CniCapabilities}},
{{- end -}}
{{- if .Bridge -}}
  "bridge":"{{.Bridge}}",
{{- end -}}
{{- if .VlanTag -}}
  "vlan":{{.VlanTag}},
{{- end -}}
{{- if .MTU -}}
  "mtu":{{.MTU}},
{{- end -}}
{{- if .Trunk -}}
  "trunk":{{.Trunk}},
{{- end -}}
{{- if .InterfaceType -}}
  "interface_type":"{{.InterfaceType}}",
{{- end -}}
  {{.CniIpam}}
}
{{- if .MetaPluginsConfigured -}}
  ,
  {{.MetaPlugins}}
  ]
}
{{- end -}}
'
