# Label PRs that touch Go test files
tests:
  - changed-files:
      - any-glob-to-any-file: "**/*_test.go"
      - any-glob-to-any-file: "test/**"

# Label PRs that touch documentation
docs:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
      - any-glob-to-any-file: "doc/**"

# Label PRs that touch GitHub workflows
ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
