// Code generated by lister-gen. DO NOT EDIT.

package v1

// SriovNetworkListerExpansion allows custom methods to be added to
// SriovNetworkLister.
type SriovNetworkListerExpansion interface{}

// SriovNetworkNamespaceListerExpansion allows custom methods to be added to
// SriovNetworkNamespaceLister.
type SriovNetworkNamespaceListerExpansion interface{}

// SriovNetworkNodePolicyListerExpansion allows custom methods to be added to
// SriovNetworkNodePolicyLister.
type SriovNetworkNodePolicyListerExpansion interface{}

// SriovNetworkNodePolicyNamespaceListerExpansion allows custom methods to be added to
// SriovNetworkNodePolicyNamespaceLister.
type SriovNetworkNodePolicyNamespaceListerExpansion interface{}

// SriovNetworkNodeStateListerExpansion allows custom methods to be added to
// SriovNetworkNodeStateLister.
type SriovNetworkNodeStateListerExpansion interface{}

// SriovNetworkNodeStateNamespaceListerExpansion allows custom methods to be added to
// SriovNetworkNodeStateNamespaceLister.
type SriovNetworkNodeStateNamespaceListerExpansion interface{}

// SriovOperatorConfigListerExpansion allows custom methods to be added to
// SriovOperatorConfigLister.
type SriovOperatorConfigListerExpansion interface{}

// SriovOperatorConfigNamespaceListerExpansion allows custom methods to be added to
// SriovOperatorConfigNamespaceLister.
type SriovOperatorConfigNamespaceListerExpansion interface{}
