/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// SriovAcceleratorNodePolicyListerExpansion allows custom methods to be added to
// SriovAcceleratorNodePolicyLister.
type SriovAcceleratorNodePolicyListerExpansion interface{}

// SriovAcceleratorNodePolicyNamespaceListerExpansion allows custom methods to be added to
// SriovAcceleratorNodePolicyNamespaceLister.
type SriovAcceleratorNodePolicyNamespaceListerExpansion interface{}

// SriovAcceleratorNodeStateListerExpansion allows custom methods to be added to
// SriovAcceleratorNodeStateLister.
type SriovAcceleratorNodeStateListerExpansion interface{}

// SriovAcceleratorNodeStateNamespaceListerExpansion allows custom methods to be added to
// SriovAcceleratorNodeStateNamespaceLister.
type SriovAcceleratorNodeStateNamespaceListerExpansion interface{}

// SriovIBNetworkListerExpansion allows custom methods to be added to
// SriovIBNetworkLister.
type SriovIBNetworkListerExpansion interface{}

// SriovIBNetworkNamespaceListerExpansion allows custom methods to be added to
// SriovIBNetworkNamespaceLister.
type SriovIBNetworkNamespaceListerExpansion interface{}

// SriovNetworkListerExpansion allows custom methods to be added to
// SriovNetworkLister.
type SriovNetworkListerExpansion interface{}

// SriovNetworkNamespaceListerExpansion allows custom methods to be added to
// SriovNetworkNamespaceLister.
type SriovNetworkNamespaceListerExpansion interface{}

// SriovNetworkNodePolicyListerExpansion allows custom methods to be added to
// SriovNetworkNodePolicyLister.
type SriovNetworkNodePolicyListerExpansion interface{}

// SriovNetworkNodePolicyNamespaceListerExpansion allows custom methods to be added to
// SriovNetworkNodePolicyNamespaceLister.
type SriovNetworkNodePolicyNamespaceListerExpansion interface{}

// SriovNetworkNodeStateListerExpansion allows custom methods to be added to
// SriovNetworkNodeStateLister.
type SriovNetworkNodeStateListerExpansion interface{}

// SriovNetworkNodeStateNamespaceListerExpansion allows custom methods to be added to
// SriovNetworkNodeStateNamespaceLister.
type SriovNetworkNodeStateNamespaceListerExpansion interface{}

// SriovOperatorConfigListerExpansion allows custom methods to be added to
// SriovOperatorConfigLister.
type SriovOperatorConfigListerExpansion interface{}

// SriovOperatorConfigNamespaceListerExpansion allows custom methods to be added to
// SriovOperatorConfigNamespaceLister.
type SriovOperatorConfigNamespaceListerExpansion interface{}
