# permissions for end users to view ovsnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovsnetwork-viewer-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - ovsnetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - ovsnetworks/status
  verbs:
  - get
