# permissions for end users to edit ovsnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:plugins:
  manifests.sdk.operatorframework.io/v2: {}
  scorecard.sdk.operatorframework.io/v2: {}
  name: ovsnetwork-editor-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - ovsnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - ovsnetworks/status
  verbs:
  - get
