# permissions for end users to view sriovoperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovoperatorconfig-viewer-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovoperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovoperatorconfigs/status
  verbs:
  - get
