# permissions for end users to view sriovibnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovibnetwork-viewer-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovibnetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovibnetworks/status
  verbs:
  - get
