# permissions for end users to view sriovnetworkpoolconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovnetworkpoolconfig-viewer-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworkpoolconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworkpoolconfigs/status
  verbs:
  - get
