# permissions for end users to view sriovnetworknodepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovnetworknodepolicy-viewer-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworknodepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworknodepolicies/status
  verbs:
  - get
