# permissions for end users to edit sriovnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovnetwork-editor-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworks/status
  verbs:
  - get
