# permissions for end users to edit sriovnetworkpoolconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovnetworkpoolconfig-editor-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworkpoolconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworkpoolconfigs/status
  verbs:
  - get
