#!/bin/bash

podman_tag_and_push() {
  local_image=$1
  cluster_image=$2

  echo "## Pushing ${local_image} to cluster registry ${cluster_image}"
  podman tag ${local_image} ${cluster_image}
  podman push --tls-verify=false ${cluster_image}
}
