apiVersion: sriovnetwork.openshift.io/v1
kind: OVSNetwork
metadata:
  name: example-ovsnetwork
spec:
  ipam: |
    {
      "type": "host-local",
      "ranges": [[{"subnet": "192.178.0.0/16"}]]
    }
  networkNamespace: default
  resourceName: switchdev-vfs
  vlan: 100
  mtu: 1500

