/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	sriovnetworkv1 "github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSriovIBNetworks implements SriovIBNetworkInterface
type FakeSriovIBNetworks struct {
	Fake *FakeSriovnetworkV1
	ns   string
}

var sriovibnetworksResource = schema.GroupVersionResource{Group: "sriovnetwork.openshift.io", Version: "v1", Resource: "sriovibnetworks"}

var sriovibnetworksKind = schema.GroupVersionKind{Group: "sriovnetwork.openshift.io", Version: "v1", Kind: "SriovIBNetwork"}

// Get takes name of the sriovIBNetwork, and returns the corresponding sriovIBNetwork object, and an error if there is any.
func (c *FakeSriovIBNetworks) Get(ctx context.Context, name string, options v1.GetOptions) (result *sriovnetworkv1.SriovIBNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sriovibnetworksResource, c.ns, name), &sriovnetworkv1.SriovIBNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sriovnetworkv1.SriovIBNetwork), err
}

// List takes label and field selectors, and returns the list of SriovIBNetworks that match those selectors.
func (c *FakeSriovIBNetworks) List(ctx context.Context, opts v1.ListOptions) (result *sriovnetworkv1.SriovIBNetworkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sriovibnetworksResource, sriovibnetworksKind, c.ns, opts), &sriovnetworkv1.SriovIBNetworkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &sriovnetworkv1.SriovIBNetworkList{ListMeta: obj.(*sriovnetworkv1.SriovIBNetworkList).ListMeta}
	for _, item := range obj.(*sriovnetworkv1.SriovIBNetworkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sriovIBNetworks.
func (c *FakeSriovIBNetworks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sriovibnetworksResource, c.ns, opts))

}

// Create takes the representation of a sriovIBNetwork and creates it.  Returns the server's representation of the sriovIBNetwork, and an error, if there is any.
func (c *FakeSriovIBNetworks) Create(ctx context.Context, sriovIBNetwork *sriovnetworkv1.SriovIBNetwork, opts v1.CreateOptions) (result *sriovnetworkv1.SriovIBNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sriovibnetworksResource, c.ns, sriovIBNetwork), &sriovnetworkv1.SriovIBNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sriovnetworkv1.SriovIBNetwork), err
}

// Update takes the representation of a sriovIBNetwork and updates it. Returns the server's representation of the sriovIBNetwork, and an error, if there is any.
func (c *FakeSriovIBNetworks) Update(ctx context.Context, sriovIBNetwork *sriovnetworkv1.SriovIBNetwork, opts v1.UpdateOptions) (result *sriovnetworkv1.SriovIBNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sriovibnetworksResource, c.ns, sriovIBNetwork), &sriovnetworkv1.SriovIBNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sriovnetworkv1.SriovIBNetwork), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSriovIBNetworks) UpdateStatus(ctx context.Context, sriovIBNetwork *sriovnetworkv1.SriovIBNetwork, opts v1.UpdateOptions) (*sriovnetworkv1.SriovIBNetwork, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sriovibnetworksResource, "status", c.ns, sriovIBNetwork), &sriovnetworkv1.SriovIBNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sriovnetworkv1.SriovIBNetwork), err
}

// Delete takes name of the sriovIBNetwork and deletes it. Returns an error if one occurs.
func (c *FakeSriovIBNetworks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sriovibnetworksResource, c.ns, name), &sriovnetworkv1.SriovIBNetwork{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSriovIBNetworks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sriovibnetworksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &sriovnetworkv1.SriovIBNetworkList{})
	return err
}

// Patch applies the patch and returns the patched sriovIBNetwork.
func (c *FakeSriovIBNetworks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *sriovnetworkv1.SriovIBNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sriovibnetworksResource, c.ns, name, pt, data, subresources...), &sriovnetworkv1.SriovIBNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sriovnetworkv1.SriovIBNetwork), err
}
