// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/openshift/sriov-network-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SriovNetworkNodeStates returns a SriovNetworkNodeStateInformer.
	SriovNetworkNodeStates() SriovNetworkNodeStateInformer
	// SriovOperatorConfigs returns a SriovOperatorConfigInformer.
	SriovOperatorConfigs() SriovOperatorConfigInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SriovNetworkNodeStates returns a SriovNetworkNodeStateInformer.
func (v *version) SriovNetworkNodeStates() SriovNetworkNodeStateInformer {
	return &sriovNetworkNodeStateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SriovOperatorConfigs returns a SriovOperatorConfigInformer.
func (v *version) SriovOperatorConfigs() SriovOperatorConfigInformer {
	return &sriovOperatorConfigInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
