// Code generated by client-gen. DO NOT EDIT.

package v1

type SriovNetworkExpansion interface{}

type SriovNetworkNodePolicyExpansion interface{}

type SriovNetworkNodeStateExpansion interface{}

type SriovOperatorConfigExpansion interface{}
