/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1"
	scheme "github.com/openshift/sriov-network-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SriovAcceleratorNodeStatesGetter has a method to return a SriovAcceleratorNodeStateInterface.
// A group's client should implement this interface.
type SriovAcceleratorNodeStatesGetter interface {
	SriovAcceleratorNodeStates(namespace string) SriovAcceleratorNodeStateInterface
}

// SriovAcceleratorNodeStateInterface has methods to work with SriovAcceleratorNodeState resources.
type SriovAcceleratorNodeStateInterface interface {
	Create(ctx context.Context, sriovAcceleratorNodeState *v1.SriovAcceleratorNodeState, opts metav1.CreateOptions) (*v1.SriovAcceleratorNodeState, error)
	Update(ctx context.Context, sriovAcceleratorNodeState *v1.SriovAcceleratorNodeState, opts metav1.UpdateOptions) (*v1.SriovAcceleratorNodeState, error)
	UpdateStatus(ctx context.Context, sriovAcceleratorNodeState *v1.SriovAcceleratorNodeState, opts metav1.UpdateOptions) (*v1.SriovAcceleratorNodeState, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SriovAcceleratorNodeState, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SriovAcceleratorNodeStateList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SriovAcceleratorNodeState, err error)
	SriovAcceleratorNodeStateExpansion
}

// sriovAcceleratorNodeStates implements SriovAcceleratorNodeStateInterface
type sriovAcceleratorNodeStates struct {
	client rest.Interface
	ns     string
}

// newSriovAcceleratorNodeStates returns a SriovAcceleratorNodeStates
func newSriovAcceleratorNodeStates(c *SriovnetworkV1Client, namespace string) *sriovAcceleratorNodeStates {
	return &sriovAcceleratorNodeStates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sriovAcceleratorNodeState, and returns the corresponding sriovAcceleratorNodeState object, and an error if there is any.
func (c *sriovAcceleratorNodeStates) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SriovAcceleratorNodeState, err error) {
	result = &v1.SriovAcceleratorNodeState{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SriovAcceleratorNodeStates that match those selectors.
func (c *sriovAcceleratorNodeStates) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SriovAcceleratorNodeStateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SriovAcceleratorNodeStateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sriovAcceleratorNodeStates.
func (c *sriovAcceleratorNodeStates) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sriovAcceleratorNodeState and creates it.  Returns the server's representation of the sriovAcceleratorNodeState, and an error, if there is any.
func (c *sriovAcceleratorNodeStates) Create(ctx context.Context, sriovAcceleratorNodeState *v1.SriovAcceleratorNodeState, opts metav1.CreateOptions) (result *v1.SriovAcceleratorNodeState, err error) {
	result = &v1.SriovAcceleratorNodeState{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sriovAcceleratorNodeState).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sriovAcceleratorNodeState and updates it. Returns the server's representation of the sriovAcceleratorNodeState, and an error, if there is any.
func (c *sriovAcceleratorNodeStates) Update(ctx context.Context, sriovAcceleratorNodeState *v1.SriovAcceleratorNodeState, opts metav1.UpdateOptions) (result *v1.SriovAcceleratorNodeState, err error) {
	result = &v1.SriovAcceleratorNodeState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		Name(sriovAcceleratorNodeState.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sriovAcceleratorNodeState).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *sriovAcceleratorNodeStates) UpdateStatus(ctx context.Context, sriovAcceleratorNodeState *v1.SriovAcceleratorNodeState, opts metav1.UpdateOptions) (result *v1.SriovAcceleratorNodeState, err error) {
	result = &v1.SriovAcceleratorNodeState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		Name(sriovAcceleratorNodeState.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sriovAcceleratorNodeState).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sriovAcceleratorNodeState and deletes it. Returns an error if one occurs.
func (c *sriovAcceleratorNodeStates) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sriovAcceleratorNodeStates) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sriovAcceleratorNodeState.
func (c *sriovAcceleratorNodeStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SriovAcceleratorNodeState, err error) {
	result = &v1.SriovAcceleratorNodeState{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sriovacceleratornodestates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
